# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import mnemos_pb2 as mnemos__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mnemos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MnemosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertMemory = channel.unary_unary(
                '/mnemos.MnemosService/InsertMemory',
                request_serializer=mnemos__pb2.InsertMemoryRequest.SerializeToString,
                response_deserializer=mnemos__pb2.InsertMemoryResponse.FromString,
                _registered_method=True)
        self.DeleteMemory = channel.unary_unary(
                '/mnemos.MnemosService/DeleteMemory',
                request_serializer=mnemos__pb2.DeleteMemoryRequest.SerializeToString,
                response_deserializer=mnemos__pb2.DeleteMemoryResponse.FromString,
                _registered_method=True)
        self.AddEdge = channel.unary_unary(
                '/mnemos.MnemosService/AddEdge',
                request_serializer=mnemos__pb2.AddEdgeRequest.SerializeToString,
                response_deserializer=mnemos__pb2.AddEdgeResponse.FromString,
                _registered_method=True)
        self.RemoveEdge = channel.unary_unary(
                '/mnemos.MnemosService/RemoveEdge',
                request_serializer=mnemos__pb2.RemoveEdgeRequest.SerializeToString,
                response_deserializer=mnemos__pb2.RemoveEdgeResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/mnemos.MnemosService/Query',
                request_serializer=mnemos__pb2.QueryRequest.SerializeToString,
                response_deserializer=mnemos__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.EnforceCapacity = channel.unary_unary(
                '/mnemos.MnemosService/EnforceCapacity',
                request_serializer=mnemos__pb2.EnforceCapacityRequest.SerializeToString,
                response_deserializer=mnemos__pb2.EnforceCapacityResponse.FromString,
                _registered_method=True)
        self.CompactSegments = channel.unary_unary(
                '/mnemos.MnemosService/CompactSegments',
                request_serializer=mnemos__pb2.CompactSegmentsRequest.SerializeToString,
                response_deserializer=mnemos__pb2.CompactSegmentsResponse.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/mnemos.MnemosService/Stats',
                request_serializer=mnemos__pb2.StatsRequest.SerializeToString,
                response_deserializer=mnemos__pb2.StatsResponse.FromString,
                _registered_method=True)


class MnemosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InsertMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnforceCapacity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompactSegments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MnemosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsertMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertMemory,
                    request_deserializer=mnemos__pb2.InsertMemoryRequest.FromString,
                    response_serializer=mnemos__pb2.InsertMemoryResponse.SerializeToString,
            ),
            'DeleteMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMemory,
                    request_deserializer=mnemos__pb2.DeleteMemoryRequest.FromString,
                    response_serializer=mnemos__pb2.DeleteMemoryResponse.SerializeToString,
            ),
            'AddEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.AddEdge,
                    request_deserializer=mnemos__pb2.AddEdgeRequest.FromString,
                    response_serializer=mnemos__pb2.AddEdgeResponse.SerializeToString,
            ),
            'RemoveEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveEdge,
                    request_deserializer=mnemos__pb2.RemoveEdgeRequest.FromString,
                    response_serializer=mnemos__pb2.RemoveEdgeResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=mnemos__pb2.QueryRequest.FromString,
                    response_serializer=mnemos__pb2.QueryResponse.SerializeToString,
            ),
            'EnforceCapacity': grpc.unary_unary_rpc_method_handler(
                    servicer.EnforceCapacity,
                    request_deserializer=mnemos__pb2.EnforceCapacityRequest.FromString,
                    response_serializer=mnemos__pb2.EnforceCapacityResponse.SerializeToString,
            ),
            'CompactSegments': grpc.unary_unary_rpc_method_handler(
                    servicer.CompactSegments,
                    request_deserializer=mnemos__pb2.CompactSegmentsRequest.FromString,
                    response_serializer=mnemos__pb2.CompactSegmentsResponse.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=mnemos__pb2.StatsRequest.FromString,
                    response_serializer=mnemos__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mnemos.MnemosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mnemos.MnemosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MnemosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InsertMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mnemos.MnemosService/InsertMemory',
            mnemos__pb2.InsertMemoryRequest.SerializeToString,
            mnemos__pb2.InsertMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mnemos.MnemosService/DeleteMemory',
            mnemos__pb2.DeleteMemoryRequest.SerializeToString,
            mnemos__pb2.DeleteMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mnemos.MnemosService/AddEdge',
            mnemos__pb2.AddEdgeRequest.SerializeToString,
            mnemos__pb2.AddEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mnemos.MnemosService/RemoveEdge',
            mnemos__pb2.RemoveEdgeRequest.SerializeToString,
            mnemos__pb2.RemoveEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mnemos.MnemosService/Query',
            mnemos__pb2.QueryRequest.SerializeToString,
            mnemos__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnforceCapacity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mnemos.MnemosService/EnforceCapacity',
            mnemos__pb2.EnforceCapacityRequest.SerializeToString,
            mnemos__pb2.EnforceCapacityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompactSegments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mnemos.MnemosService/CompactSegments',
            mnemos__pb2.CompactSegmentsRequest.SerializeToString,
            mnemos__pb2.CompactSegmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mnemos.MnemosService/Stats',
            mnemos__pb2.StatsRequest.SerializeToString,
            mnemos__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
